parameters:
#    book_fair_bookshop.example.class: BookFair\Bundle\BookshopBundle\Example

services:
#    book_fair_bookshop.example:
#        class: %book_fair_bookshop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
